Merge upstream/v4.2.1 onto theslinux (except: makepkg)
The script "makepkg" is excluded because there are a lot of changes
in #theslinux branch. We may take a look (carefully) in the future.

diff --git a/contrib/bacman.sh.in b/contrib/bacman.sh.in
--- a/contrib/bacman.sh.in
+++ b/contrib/bacman.sh.in
@@ -5,7 +5,7 @@
 #   stored into the pacman database and system files
 #
 #   Copyright (c) 2008 locci <carlocci_at_gmail_dot_com>
-#   Copyright (c) 2008-2013 Pacman Development Team <pacman-dev@archlinux.org>
+#   Copyright (c) 2008-2014 Pacman Development Team <pacman-dev@archlinux.org>
 #
 #   This program is free software; you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
@@ -27,6 +27,9 @@ shopt -s nullglob
 declare -r myname='bacman'
 declare -r myver='@PACKAGE_VERSION@'
 USE_COLOR='y'
+INCLUDE_PACNEW='n'
+# Required for fakeroot because options are shifted off the array.
+ARGS=("$@")
 
 m4_include(../scripts/library/output_format.sh)
 
@@ -34,20 +37,32 @@ m4_include(../scripts/library/output_format.sh)
 # User Friendliness
 #
 usage() {
-	echo "This program recreates a package using pacman's db and system files"
-	echo "Usage:   $myname [--nocolor] <installed package name>"
-	echo "Example: $myname kernel26"
+	echo "${myname} (pacman) v${myver}"
+	echo
+	echo "Recreate a package using pacman's database and system files"
+	echo
+	echo "Usage: ${myname} [--nocolor] [--pacnew] <installed package name>"
+	echo
+	echo "Example: ${myname} linux-headers"
 }
 
 version() {
 	printf "%s %s\n" "$myname" "$myver"
 	echo 'Copyright (C) 2008 locci <carlocci_at_gmail_dot_com>'
+	echo 'Copyright (C) 2008-2014 Pacman Development Team <pacman-dev@archlinux.org>'
 }
 
-if [[ $1 == "--nocolor" ]]; then
-	USE_COLOR='n'
-	shift
-fi
+while [[ ! -z $1 ]]; do
+	if [[ $1 == "--nocolor" ]]; then
+		USE_COLOR='n'
+		shift
+	elif [[ $1 == "--pacnew" ]]; then
+		INCLUDE_PACNEW='y'
+		shift
+	else
+		break
+	fi
+done
 
 m4_include(../scripts/library/term_colors.sh)
 
@@ -71,7 +86,7 @@ if (( EUID )); then
 	if [[ -f /usr/bin/fakeroot ]]; then
 		msg "Entering fakeroot environment"
 		export INFAKEROOT="1"
-		/usr/bin/fakeroot -u -- "$0" "$@"
+		/usr/bin/fakeroot -u -- "$0" "${ARGS[@]}"
 		exit $?
 	else
 		warning "installing fakeroot or running $myname as root is required to"
@@ -124,7 +139,7 @@ fi
 
 if [[ ! -d $pkg_dir ]]; then
 	error "package %s is found in pacman database," "${pkg_name}"
-	plain "       but \`%s' is not a directory" "${pkg_dir}"
+	plain "       but '%s' is not a directory" "${pkg_dir}"
 	exit 1
 fi
 
@@ -140,7 +155,6 @@ cd "$work_dir" || exit 1
 #
 msg2 "Copying package files..."
 
-cat "$pkg_dir"/files |
 while read i; do
 	if [[ -z $i ]]; then
 		continue
@@ -153,24 +167,55 @@ while read i; do
 
 	case "$current" in
 		%FILES%)
-			ret=0
-			if [[ -e /$i ]]; then
-				bsdtar -cnf - "/$i" 2> /dev/null | bsdtar -xpf -
+			local_file="/$i"
+			package_file="$work_dir/$i"
 
-				# Workaround to bsdtar not reporting a missing file as an error
-				if ! [[ -e $work_dir/$i || -L $work_dir/$i ]]; then
-					error "unable to add /$i to the package"
-					plain "       If your user does not have permssion to read this file then"
-					plain "       you will need to run $myname as root"
-					rm -rf "$work_dir"
-					exit 1
-				fi
-			else
-				warning "package file /$i is missing"
+			if [[ ! -e $local_file ]]; then
+				warning "package file $local_file is missing"
+				continue
 			fi
 			;;
+
+		%BACKUP%)
+			# Get the MD5 checksum.
+			original_md5="${i##*$'\t'}"
+			# Strip the md5sum after the tab.
+			i="${i%$'\t'*}"
+			local_file="/$i.pacnew"
+			package_file="$work_dir/$i"
+
+			# Include unmodified .pacnew files.
+			local_md5="$(md5sum "$local_file" | cut -d' ' -f1)"
+			if [[ $INCLUDE_PACNEW == 'n' ]] \
+			|| [[ ! -e $local_file ]] \
+			|| [[ $local_md5 != $original_md5 ]]; then
+				# Warn about modified files.
+				local_md5="$(md5sum "/$i" | cut -d' ' -f1)"
+				if [[ $local_md5 != $original_md5 ]]; then
+					warning "package file /$i has been modified"
+				fi
+				# Let the normal file be included in the %FILES% list.
+				continue
+			fi
+			;;
+
+		*)
+			continue
+			;;
 	esac
-done
+
+	ret=0
+	bsdtar -cnf - -s'/.pacnew$//' "$local_file" 2> /dev/null | bsdtar -xpf - 2> /dev/null
+
+	# Workaround to bsdtar not reporting a missing file as an error
+	if ! [[ -e $package_file || -L $package_file ]]; then
+		error "unable to add $local_file to the package"
+		plain "       If your user does not have permission to read this file, then"
+		plain "       you will need to run $myname as root."
+		rm -rf "$work_dir"
+		exit 1
+	fi
+done < "$pkg_dir"/files
 
 ret=$?
 if (( ret )); then
@@ -253,7 +298,7 @@ while read i; do
 
 		# files
 		%BACKUP%)
-			# strip the md5sum after the tab
+			# Strip the md5sum after the tab
 			echo "backup = ${i%%$'\t'*}"   >> .PKGINFO
 			;;
 	esac
@@ -310,4 +355,4 @@ msg "Done."
 
 exit 0
 
-# vim: set ts=2 sw=2 noet:
+# vim: set noet:
diff --git a/contrib/paccache.sh.in b/contrib/paccache.sh.in
--- a/contrib/paccache.sh.in
+++ b/contrib/paccache.sh.in
@@ -23,9 +23,9 @@ shopt -s extglob
 declare -r myname='paccache'
 declare -r myver='@PACKAGE_VERSION@'
 
-declare -a candidates=() cmdopts=() whitelist=() blacklist=()
+declare -a cachedirs=() candidates=() cmdopts=() whitelist=() blacklist=()
 declare -i delete=0 dryrun=0 filecount=0 move=0 needsroot=0 totalsaved=0 verbose=0
-declare    cachedir=@localstatedir@/cache/pacman/pkg delim=$'\n' keep=3 movedir= scanarch=
+declare    delim=$'\n' keep=3 movedir= scanarch=
 
 USE_COLOR='y'
 
@@ -37,15 +37,33 @@ die() {
 	exit 1
 }
 
+get_cachedir_from_config() {
+	local key value
+
+	while IFS=$'= \t' read -r key value _; do
+		if [[ $key = CacheDir ]]; then
+			echo "$value"
+			return 0
+		fi
+	done <"$1"
+
+	return 1
+}
+
 # reads a list of files on stdin and prints out deletion candidates
 pkgfilter() {
 	# there's whitelist and blacklist parameters passed to this
 	# script after the block of awk.
 
 	awk -v keep="$1" -v scanarch="$2" '
+	function basename(str) {
+		sub(".*/", "", str);
+		return str;
+	}
+
 	function parse_filename(filename,     parts, count, i, pkgname, arch) {
 
-		count = split(filename, parts, "-")
+		count = split(basename(filename), parts, "-")
 
 		i = 1
 		pkgname = parts[i++]
@@ -109,8 +127,7 @@ runcmd() {
 		if sudo -v &>/dev/null && sudo -l &>/dev/null; then
 			sudo "$@"
 		else
-			printf '%s ' 'root'
-			su -c "$(printf '%q ' "$@")"
+			die 'Unable to escalate privileges using sudo'
 		fi
 	else
 		"$@"
@@ -134,48 +151,51 @@ summarize() {
 					[[ $pkg =~ $pkg_re ]] && name=${BASH_REMATCH[1]} arch=${BASH_REMATCH[2]}
 					if [[ -z $seen || $seenarch != "$arch" || $seen != "$name" ]]; then
 						seen=$name seenarch=$arch
-						printf '%s (%s):\n' "$name" "$arch"
+						printf '%s (%s):\n' "${name##*/}" "$arch"
 					fi
-					printf '  %s\n' "$pkg"
+					printf '  %s\n' "${pkg##*/}"
 				elif (( verbose >= 2 )); then
-					printf "$PWD/%s$delim" "$pkg"
-				else
 					printf "%s$delim" "$pkg"
+				else
+					printf "%s$delim" "${pkg##*/}"
 				fi
 			done < <(printf '%s\n' "$@" | pacsort --files)
 		fi
 		printf -v output 'finished dry run: %d candidates' "$filecount"
 	fi
 
-	printf '\n' >&2
-	msg "$output (diskspace saved: %s)" "$(size_to_human "$totalsaved")"
+	echo
+	msg "$output (disk space saved: %s)" "$(size_to_human "$totalsaved")"
 }
 
 usage() {
 	cat <<EOF
-usage: $myname <operation> [options] [targets...]
+${myname} (pacman) v${myver}
 
-$myname is a flexible pacman cache cleaning utility, which has numerous
-options to help control how much, and what, is deleted from any directory
-containing pacman package tarballs.
+A flexible pacman cache cleaning utility.
+
+Usage: ${myname} <operation> [options] [targets...]
 
   Operations:
-    -d, --dryrun            perform a dry run, only finding candidate packages.
-    -m, --move <dir>        move candidate packages to 'movedir'.
-    -r, --remove            remove candidate packages.
+    -d, --dryrun          perform a dry run, only finding candidate packages.
+    -m, --move <dir>      move candidate packages to "dir".
+    -r, --remove          remove candidate packages.
 
   Options:
-    -a, --arch <arch>       scan for 'arch' (default: all architectures).
-    -c, --cachedir <dir>    scan 'cachedir' for packages (default: @localstatedir@/cache/pacman/pkg).
-    -f, --force             apply force to mv(1) and rm(1) operations.
-    -h, --help              display this help message and exit.
-    -i, --ignore <pkgs>     ignore 'pkgs', comma separated. Alternatively, specify '-' to
-                              read package names from stdin, newline delimited.
-    -k, --keep <num>        keep 'num' of each package in 'cachedir' (default: 3).
-    --nocolor               remove color from output.
-    -u, --uninstalled       target uninstalled packages.
-    -v, --verbose           increase verbosity. specify up to 3 times.
-    -z, --null              use null delimiters for candidate names (only with -v and -vv)
+    -a, --arch <arch>     scan for "arch" (default: all architectures).
+    -c, --cachedir <dir>  scan "dir" for packages. can be used more than once.
+                          (default: read from @sysconfdir@/pacman.conf).
+    -f, --force           apply force to mv(1) and rm(1) operations.
+    -h, --help            display this help message and exit.
+    -i, --ignore <pkgs>   ignore "pkgs", comma-separated. Alternatively, specify
+                          "-" to read package names from stdin, newline-
+                          delimited.
+    -k, --keep <num>      keep "num" of each package in the cache (default: 3).
+        --nocolor         remove color from output.
+    -u, --uninstalled     target uninstalled packages.
+    -v, --verbose         increase verbosity. specify up to 3 times.
+    -z, --null            use null delimiters for candidate names (only with -v
+                          and -vv).
 
 EOF
 }
@@ -201,7 +221,7 @@ while :; do
 			scanarch=$2
 			shift ;;
 		-c|--cachedir)
-			cachedir=$2
+			cachedirs+=("$2")
 			shift ;;
 		-d|--dryrun)
 			dryrun=1 ;;
@@ -236,6 +256,8 @@ while :; do
 			delete=1 ;;
 		-u|--uninstalled)
 			IFS=$'\n' read -r -d '' -a ign < <(pacman -Qq)
+			# pacman -Qq may exit with an error, thus making ign an empty array
+			(( ${#ign[@]} )) || die 'failed to retrieve the list of installed packages'
 			blacklist+=("${ign[@]}")
 			unset ign ;;
 		-V|--version)
@@ -254,6 +276,15 @@ done
 
 m4_include(../scripts/library/term_colors.sh)
 
+# setting default cachedir
+if [[ -z $cachedirs ]]; then
+	if cachedir=$(get_cachedir_from_config "@sysconfdir@/pacman.conf"); then
+		cachedirs=("$cachedir")
+	else
+		cachedirs=("${cachedirs[@]:-@localstatedir@/cache/pacman/pkg}")
+	fi
+fi
+
 # remaining args are a whitelist
 whitelist=("$@")
 
@@ -263,32 +294,43 @@ case $(( dryrun+delete+move )) in
 	[^1]) die "only one operation may be used at a time" ;;
 esac
 
-[[ -d $cachedir ]] ||
-	die "cachedir '%s' does not exist or is not a directory" "$cachedir"
-
 [[ $movedir && ! -d $movedir ]] &&
-	die "move-to directory '%s' does not exist or is not a directory" "$movedir"
+	die "destination directory '%s' does not exist or is not a directory" "$movedir"
 
 if (( move || delete )); then
 	# make it an absolute path since we're about to chdir
-	[[ ${movedir:0:1} != '/' ]] && movedir=$PWD/$movedir
-	[[ ! -w $cachedir || ( $movedir && ! -w $movedir ) ]] && needsroot=1
+	[[ $movedir && ${movedir:0:1} != '/' ]] && movedir=$PWD/$movedir
+	[[ $movedir && ! -w $movedir ]] && needsroot=1
 fi
 
-# unlikely that this will fail, but better make sure
-cd "$cachedir" >/dev/null || die "failed to chdir to '%s'" "$cachedir"
+for cachedir in "${cachedirs[@]}"; do
+	[[ -d $cachedir ]] ||
+		die "cachedir '%s' does not exist or is not a directory" "$cachedir"
 
-# note that these results are returned in an arbitrary order from awk, but
-# they'll be resorted (in summarize) iff we have a verbosity level set.
-IFS=$'\n' read -r -d '' -a candidates < \
-	<(printf '%s\n' *.pkg.tar?(.+([^.])) | pacsort --files |
-		pkgfilter "$keep" "$scanarch" \
-			"${#whitelist[*]}" "${whitelist[@]}" \
-			"${#blacklist[*]}" "${blacklist[@]}")
+	if (( move || delete )); then
+		[[ ! -w $cachedir ]] && needsroot=1
+	fi
+
+	# unlikely that this will fail, but better make sure
+	pushd "$cachedir" &>/dev/null || die "failed to chdir to '%s'" "$cachedir"
+
+	# note that these results are returned in an arbitrary order from awk, but
+	# they'll be resorted (in summarize) iff we have a verbosity level set.
+	IFS=$'\n' read -r -d '' -a cand < \
+		<(printf '%s\n' "$PWD"/*.pkg.tar?(.+([^.])) | pacsort --files |
+			pkgfilter "$keep" "$scanarch" \
+				"${#whitelist[*]}" "${whitelist[@]}" \
+				"${#blacklist[*]}" "${blacklist[@]}")
+
+	candidates+=("${cand[@]}")
+	unset cand
+
+	popd &>/dev/null
+done
 
 if (( ! ${#candidates[*]} )); then
 	msg 'no candidate packages found for pruning'
-	exit 1
+	exit 0
 fi
 
 # grab this prior to signature scavenging
@@ -296,8 +338,8 @@ pkgcount=${#candidates[*]}
 
 # copy the list, merging in any found sigs
 for cand in "${candidates[@]}"; do
-  candtemp+=("$cand")
-  [[ -f $cand.sig ]] && candtemp+=("$cand.sig")
+	candtemp+=("$cand")
+	[[ -f $cand.sig ]] && candtemp+=("$cand.sig")
 done
 candidates=("${candtemp[@]}")
 unset candtemp
@@ -315,4 +357,4 @@ fi
 
 summarize "$pkgcount" "${candidates[@]}"
 
-# vim: set ts=2 sw=2 noet:
+# vim: set noet:
diff --git a/contrib/pacscripts.sh.in b/contrib/pacscripts.sh.in
--- a/contrib/pacscripts.sh.in
+++ b/contrib/pacscripts.sh.in
@@ -5,6 +5,7 @@
 #
 #   Copyright (c) 2009 Giulio "giulivo" Fidente <giulivo.navigante@gmail.com>
 #   Copyright (c) 2009 Xavier Chantry <shiningxc@gmail.com>
+#   Copyright (c) 2009-2014 Pacman Development Team <pacman-dev@archlinux.org>
 #
 #   This program is free software; you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
@@ -45,16 +46,18 @@ error() {
 }
 
 usage() {
-	echo "This program prints out the {pre,post}_{install,remove,upgrade} scripts"
-	echo "of a given package."
-	echo "Usage: $myname pkgname|pkgfile"
+	echo "${myname} (pacman) v${myver}"
 	echo
-	echo " OPTIONS:"
+	echo "Prints the {pre,post}_{install,remove,upgrade} scripts of a given package."
+	echo
+	echo "Usage: ${myname} <pkgname|pkgfile>"
+	echo
+	echo " Options:"
 	echo "  -h, --help                 Print this help message"
 	echo "  -v, --version              Print program name and version"
 	echo
-	echo "Example: $myname gconf-editor"
-	echo "Example: $myname gconf-editor-2.24.1-1-x86_64.pkg.tar.gz"
+	echo "Example: ${myname} gconf-editor"
+	echo "Example: ${myname} gconf-editor-3.0.1-3-x86_64.pkg.tar.xz"
 }
 
 version() {
@@ -68,8 +71,8 @@ spacman() {
 		pacman "$@"
 	else
 		if ! type -p sudo; then
-			error "Cannot find the sudo binary! Is sudo installed?"
-			error "Otherwise try to run the program as root"
+			error "Cannot find the sudo binary!"
+			error "${myname} requires root privileges. Either install \"sudo\" or run as root."
 			exit 1
 		else
 			sudo pacman "$@"
@@ -91,7 +94,7 @@ print_db() {
 }
 
 print_pkg() {
-	if ! bsdtar -xOf "$1" .INSTALL 2>/dev/null; then
+	if ! bsdtar -xqOf "$1" .INSTALL 2>/dev/null; then
 		error "Package $1 does not include any .INSTALL script"
 		return 1
 	fi
@@ -113,10 +116,10 @@ print_scriptlet() {
 		error "Package $1 not found"
 		return 1
 	fi
-	url=$(spacman -Sdp $1 | tail -n1)
+	url=$(pacman -Sddp $1)
 	filename=$(basename $url)
 	if [ ! -f "$pac_cache/$filename" ]; then
-		if ! spacman -Sdw --noconfirm $1 >&2; then
+		if ! spacman -Sddw --noconfirm $1 >&2; then
 			error "Failed to download $1"
 			return 1
 		fi
diff --git a/contrib/rankmirrors.sh.in b/contrib/rankmirrors.sh.in
--- a/contrib/rankmirrors.sh.in
+++ b/contrib/rankmirrors.sh.in
@@ -21,26 +21,31 @@
 # traps interrupt key to spit out pre-interrupt info
 trap finaloutput INT
 
+declare -r myname='rankmirrors'
+declare -r myver='@PACKAGE_VERSION@'
+
 usage() {
-	echo "Usage: rankmirrors [options] MIRRORFILE | URL"
+	echo "${myname} (pacman) v${myver}"
 	echo
 	echo "Ranks pacman mirrors by their connection and opening speed. Pacman mirror"
 	echo "files are located in @sysconfdir@/pacman.d/. It can also rank one mirror if the URL is"
 	echo "provided."
+	echo
+	echo "Usage: ${myname} [options] MIRRORFILE | URL"
 	echo
 	echo "Options:"
 	echo "  --version      show program's version number and exit"
 	echo "  -h, --help     show this help message and exit"
 	echo "  -n NUM         number of servers to output, 0 for all"
 	echo "  -t, --times    only output mirrors and their response times"
-	echo "  -u, --url      test a specific url"
+	echo "  -u, --url      test a specific URL"
 	echo "  -v, --verbose  be verbose in ouptut"
-	echo "  -r, --repo     specify a specific repo name instead of guessing"
+	echo "  -r, --repo     specify a repository name instead of guessing"
 	exit 0
 }
 
 version() {
-	echo "rankmirrors (pacman) @PACKAGE_VERSION@"
+	echo "${myname} (pacman) ${myver}"
 	echo "Copyright (c) 2009 Matthew Bruenig <matthewbruenig@gmail.com>."
 	echo
 	echo "This is free software; see the source for copying conditions."
@@ -125,9 +130,16 @@ while [[ $1 ]]; do
 			version) version ;;
 			times) TIMESONLY=1 ; shift ;;
 			verbose) VERBOSE=1 ; shift ;;
-			url) CHECKURL=1; [[ $2 ]] || err "Must specify url."; URL="$2"; shift 2;;
-			repo) [[ $2 ]] || err "Must specify repo name."; TARGETREPO="$2"; shift 2;;
-			*) err "\`$1' is an invalid argument."
+			url)
+				CHECKURL=1;
+				[[ $2 ]] || err "Must specify URL.";
+				URL="$2";
+				shift 2;;
+			repo)
+				[[ $2 ]] || err "Must specify repository name.";
+				TARGETREPO="$2";
+				shift 2;;
+			*) err "'$1' is an invalid argument."
 		esac
 	elif [[ ${1:0:1} = - ]]; then
 
@@ -143,10 +155,20 @@ while [[ $1 ]]; do
 					h) usage ;;
 					t) TIMESONLY=1 ;;
 					v) VERBOSE=1 ;;
-					u) CHECKURL=1; [[ $2 ]] || err "Must specify url."; URL="$2"; snum=2;;
-					r) [[ $2 ]] || err "Must specify repo name."; TARGETREPO="$2"; snum=2;;
-					n) [[ $2 ]] || err "Must specify number." ; NUM="$2" ; snum=2;;
-					*) err "\`-$1' is an invald argument." ;;
+					u)
+						CHECKURL=1;
+						[[ $2 ]] || err "Must specify URL.";
+						URL="$2";
+						snum=2;;
+					r)
+						[[ $2 ]] || err "Must specify repository name.";
+						TARGETREPO="$2";
+						snum=2;;
+					n)
+						[[ $2 ]] || err "Must specify number.";
+						NUM="$2";
+						snum=2;;
+					*) err "'$1' is an invalid argument." ;;
 				esac
 			done
 			shift $snum
@@ -157,34 +179,34 @@ while [[ $1 ]]; do
 		[[ $linearray ]] || err "File is empty."
 		shift
 	else
-		err "\`$1' does not exist."
+		err "'$1' does not exist."
 	fi
 done
 
 # Some sanity checks
 [[ $NUM ]] || NUM=0
-[[ $FILE && $CHECKURL ]] && err "Cannot specify a url and mirrorfile."
-[[ $FILE || $CHECKURL || $STDIN ]] || err "Must specify url, mirrorfile, or stdin."
+[[ $FILE && $CHECKURL ]] && err "Cannot specify a URL and mirrorfile."
+[[ $FILE || $CHECKURL || $STDIN ]] || err "Must specify URL, mirrorfile, or stdin."
 
-# Single url handling
+# Single URL handling
 if [[ $CHECKURL ]]; then
 	url="$(getfetchurl "$URL")"
-	[[ $url = fail ]] && err "url \`$URL' is malformed."
+	[[ $url = fail ]] && err "URL '$URL' is malformed."
 	[[ $VERBOSE ]] && echo "Testing $url..."
 	time=$(gettime "$url")
 	echo "$URL : $time"
 	exit 0
 fi
 
-# Get url results from mirrorfile, fill up the array, and so on
+# Get URL results from mirrorfile, fill up the array, and so on
 if [[ $TIMESONLY ]]; then
-	echo "Querying servers, this may take some time..."
+	echo "Querying servers. This may take some time..."
 elif [[ $FILE ]]; then
 	echo "# Server list generated by rankmirrors on $(date +%Y-%m-%d)"
 fi
 
 timesarray=()
-for line in  "${linearray[@]}"; do
+for line in "${linearray[@]}"; do
 	if [[ $line =~ ^[[:space:]]*# ]]; then
 		[[ $TIMESONLY ]] || echo $line
 	elif [[ $line =~ ^[[:space:]]*Server ]]; then
@@ -193,7 +215,7 @@ for line in  "${linearray[@]}"; do
 		server="${line#*= }"
 		server="${server%%#*}"
 		url="$(getfetchurl "$server")"
-		[[ $url = fail ]] && err "url \`$URL' is malformed."
+		[[ $url = fail ]] && err "URL '$URL' is malformed."
 		time=$(gettime "$url")
 		timesarray+=("$time $server")
 
@@ -209,4 +231,4 @@ for line in  "${linearray[@]}"; do
 done
 finaloutput
 
-# vim: set ts=2 sw=2 noet:
+# vim: set noet:
